### ISSUE TITLE
Cannot write id3v2 tag

### ISSUE THREAD

**Issue by alcohol** [squell/id3#4] opened 2015-11-23 13:25 UTC
The existing file already has a id3v2.4 tag. I know `id3` can only read those, not write to those. Is there a way I can simply remove the id3v2.4 tag and write a id3v2.3 tag instead?

I've Google'd myself senseless, but cannot find any command line tool that will let me completely remove the id3 tags, allowing me to re-tag them using `id3`.

**Comment by squell** [comment] 2015-12-02 17:55
It was intended that 0.78 could also remove those, and convert them to ID3v2.3 upon modification; but a safety check prevented the final _write_ action of this. This is fixed in the current HEAD.

With this fix, it's not necessary to remove v2.4 and then add v2.3; just forcing a write operation on a id3v2 tag should be enough. For example: `id3 -2 -u file.mp3`.

**Closed as completed** 2015-12-02 17:55 UTC
Labels: bug
