### ISSUE TITLE
id3 0.80 changes console codepage from OEM to ANSI

### ISSUE THREAD

**Issue by WonderRat** [squell/id3#5] opened 2016-03-04 01:56 UTC
Windows XP SP3

```
>chcp
Текущая кодовая страница: 866

>id3.exe -V
id3 0.80 (2015356), Copyright (C) 2003, 04, 05, 06, 15 Marc R. Schoolderman
This program comes with ABSOLUTELY NO WARRANTY.

This is free software, and you are welcome to redistribute it
under certain conditions; see the file named COPYING in the
source distribution for details.

>chcp
╥хъє∙р  ъюфютр  ёЄЁрэшЎр: 1251
```

**Comment by squell** [comment] 2016-03-04 13:57
Confirmed. This is caused by exit() bypassing a destructor which should return the codepage to its previous value.

**Comment by squell** [comment] 2016-11-15 00:08
Fixed in commit 53c538f4db309b6907793e0e68f277a7d6a046f4

**Closed as completed by squell** 2016-11-15 00:08 UTC
Labels: bug
